Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports DevExpress.DataAccess
Imports DevExpress.DashboardCommon

Namespace Win_Dashboards
    Partial Public Class adminDB
        Inherits DevExpress.DashboardCommon.Dashboard
        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            Student_marksTableAdapter1.Fill(Result_db1DataSet1.student_marks)
        End Sub
    End Class
End Namespace