Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text
Imports System.Threading.Tasks
Imports DevExpress.DataAccess
Imports DevExpress.DashboardCommon

Namespace Win_Dashboards
    Partial Public Class subjectTeacherDB
        Inherits DevExpress.DashboardCommon.Dashboard
        Public Sub New(ByVal year As String, term As String, staff_id As String)
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            Student_marksTableAdapter1.FillByYTStaff(Result_db1DataSet1.student_marks, year, term, staff_id)
        End Sub
    End Class
End Namespace